services:
  accounts:
    container_name: accounts-ms
    image: "suhwan22/accounts:s4"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybanks
  loans:
    container_name: loans-ms
    image: "suhwan22/loans:s4"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybanks
  cards:
    container_name: cards-ms
    image: "suhwan22/cards:s4"
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybanks

networks:
  eazybanks:
    driver: "bridge"